#!/bin/sh

. /etc/include/basicrc
. /etc/include/choupi
. /etc/include/mount9p
. /etc/include/pkgin

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/pkg/bin:/usr/pkg/sbin
export TERM=tmux-256color
sqldir="/mnt/sql"
wwwdir="/mnt/www"
wwwroot="/var/www"

load_sql()
{
	echo "${INFO} loading sql files..."
	for sql in ${sqldir}/*.sql; do
		echo -e " \t${ARROW} processing '$(basename $sql)'"
		#mariadb -S /tmp/mysql.sock < $sql
		mariadb < $sql
	done
}

hostname nbmp
 
# A SUPPRIMER
echo "alias ll='ls -al'" > /etc/profile
echo "alias stop='/etc/rc.d/mariadb stop'" >> /etc/profile


if ! id mariadb >/dev/null 2>&1; then
	echo "${ARROW} MariaDB server settings"
	groupadd mariadb
	useradd -g mariadb -m -d /var/db/mariadb -s /bin/sh -c "MariaDB administrator" mariadb
	install -d -o mariadb -g mariadb -m 0700 /var/db/mariadb /var/log/mariadb
	install -d -o mariadb -g mariadb -m 755 /var/run/mariadb
	install -o mariadb -g mariadb -m 750 /dev/null /var/log/mariadb/error.log
	cp /usr/pkg/share/examples/rc.d/mariadb /etc/rc.d/mariadb
	echo "mariadb=yes" >> /etc/rc.conf
	
	echo "${ARROW} Bozohttpd settings"
	rmdir ${wwwroot}
	ln -snf ${wwwdir} ${wwwroot}
fi

echo "${ROCKET} MariaDB launching..."
/etc/rc.d/mariadb start >/dev/null 2>&1
exitCode=$?
sleep 2

if [ ${exitCode} -ne 0 ]; then
	echo -e "${ERROR} MariaDB is not running.\nExit\n\n"
	return -1
fi


if [ -f /mnt/sql/nodeletesql ]; then
	echo "${INFO} use 'nodeletesql' file -> do nothing with sql..."
else
	echo "${INFO} drop existing databases..."
	dbs=$(mariadb -B -s -e "show databases" | grep -vE "(information_schema|performance_schema|sys|mysql|test)")
	for db in ${dbs}; do
		mariadb -e "drop database ${db}"
	done

	load_sql
fi

echo "${ROCKET} bozohttpd launching..."
/usr/libexec/bozohttpd -b -x index.php -C .php /usr/pkg/libexec/cgi-bin/php84 /var/www/

echo -e "\n\n${ROCKET} Ready to be used !\n\n"

echo -e "(use http://localhost:8181 by default to see your www pages)\n\n"
bash

. /etc/include/shutdown
